[project]
name = "deepseek-engineer-gui"
version = "0.1.1"
description = "Implemented a GUI using customtkinter for the DeepSeek Engineer command line interface."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.58.1",
    "prompt-toolkit>=3.0.50",
    "pydantic>=2.10.4",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"
